### ISSUE TITLE
How to download Assets from SWDC

### ISSUE THREAD

**Issue by SvenBunge** [redhat-sap/rh_operations#107]
How can I download any asset from SWDC like the ERP core files? Is the role `sap.sap_operations.download` the right role for this?

Can you please post an example? Thanks!

**Comment by kksat** [comment]
Hello, Sven 
Thank you for your question

Yes, role sap.sap_operations.download might be the right role for that. When I designed the role, my thoughts were to explicitly limit what can be downloaded with the role. So at the moment only certain software can be downloaded 

See https://docs.galaxy.saponrhel.org/collections/sap/sap_operations/download_role.html#parameter-main--download_alias

```text
Alias of SAP software that will be downloaded.
Choices:
"sapcar-7.53"
"sapcar-7.22"
"saphostagent-7.22"
"hana-server"
"hana-client"
"hana-cockpit"
"swpm-1.0"
"swpm-2.0"
```

If you want something else to be downloaded, please let me know. Having direct url to what you want to download will help greatly.
I will release new patch shortly with new alias to download what you need. 

Another way to download binaries from SWDC might be to use role sap.sap_operations.downloadbasket

See documentation https://docs.galaxy.saponrhel.org/collections/sap/sap_operations/downloadbasket_role.html#ansible-collections-sap-sap-operations-downloadbasket-role

Here is an example playbook
```yaml
- name: Download software with sap.sap_operations.downloadbasket
  gather_facts: false
  hosts: localhost
  vars:
    downloadbasket_destination: /tmp/downloadbasket
    downloadbasket_username: "<suser email>"
    downloadbasket_password: "<suser password>"
  tasks:
    - name: Create downloadbasket_destination folder
      ansible.builtin.file:
        name: "{{ downloadbasket_destination }}"
        state: directory

    - name: Run downloadbasket role
      ansible.builtin.include_role:
        name: sap.sap_operations.downloadbasket
```

You do not have to provide username and password directly in the playbook, instead you can store them in environment variables SAP_OPERATIONS_DOWNLOAD_USERNAME and SAP_OPERATIONS_DOWNLOAD_PASSWORD as mentioned in the documentation. These environment variables should be set on the controller host, not on the managed host. 

Feel free to ask any clarifying questions.
